#!/sbin/sh

set -eu

OUTFD=$2
ZIPFILE=$3
TMPDIR="/tmp/install"

ui_print() {
        echo "ui_print $1" >"/proc/self/fd/$OUTFD"
}
ui_print_abort() {
        ui_print "$1"
        exit 1
}

if [ ! -e /dev/block/by-name/linux ]; then
        ui_print_abort "Linux partition not found"
fi
if [ ! -e /dev/block/by-name/esp ]; then
        ui_print_abort "ESP partition not found"
fi

rm -rf "$TMPDIR"
mkdir -p "$TMPDIR"
cd "$TMPDIR"

ui_print "Deploying binary files..."
unzip -o "$ZIPFILE" "bin/*" -d "$TMPDIR"
chmod -R 0777 "$TMPDIR/bin"

ui_print "Formatting and flashing Linux image"
umount -lf /dev/block/by-name/linux 2>/dev/null || true
blockdev --setrw /dev/block/by-name/linux
"$TMPDIR/bin/mke2fs" -F -t ext4 /dev/block/by-name/linux
"$TMPDIR/bin/7zzs" e -so "$ZIPFILE" "images/rootfs.img" >/dev/block/by-name/linux
umount -lf /dev/block/by-name/linux 2>/dev/null || true
ui_print "Done flashing rootfs!"

ui_print "Verifying present bootloader configration"
umount -lf /dev/block/by-name/esp 2>/dev/null || true
mkdir -p "$TMPDIR/esp"
mount /dev/block/by-name/esp "$TMPDIR/esp"
rm -rf "$TMPDIR/esp/EFI"
# mkdir -p "$TMPDIR/esp/EFI"
# NOTE: it also create a folder `$TMPDIR/esp/efi`
unzip -o "$ZIPFILE" "efi/*" -d "$TMPDIR/esp"
umount -lf /dev/block/by-name/esp 2>/dev/null || true
ui_print "Boot configuration setup completed!"

ui_print "Unpacking the DBKP installer..."
unzip -o "$ZIPFILE" "DBKP/*" -d "$TMPDIR"
DBKP_uefipayload=$( (ls "$TMPDIR/DBKP"/*_EFI.fd) 2>/dev/null)
DBKP_cfg=$( (ls "$TMPDIR/DBKP"/DualBoot.*.cfg) 2>/dev/null)
DBKP_shellcode=$( (ls "$TMPDIR/DBKP"/ShellCode.*.bin) 2>/dev/null)
chmod 755 "$TMPDIR/DBKP/magiskboot"
chmod 755 "$TMPDIR/DBKP/DualBootKernelPatcher"

ui_print "Get boot.img and backup it to /sdcard/boot.img..."
dd if=/dev/block/bootdevice/by-name/boot of="$TMPDIR/boot.img"
rm -f /sdcard/boot.img
cp "$TMPDIR/boot.img" /sdcard/boot.img

ui_print "Repacking boot.img..."
mkdir -p "$TMPDIR/repack"
cd "$TMPDIR/repack"
"$TMPDIR/DBKP/magiskboot" unpack -h "$TMPDIR/boot.img"
# NOTE: Usage: <Kernel Image to Patch> <UEFI FD Image> <Patched Kernel Image Destination> <Config File> <Shell Code File>
"$TMPDIR/DBKP/DualBootKernelPatcher" "$TMPDIR/repack/kernel" "$DBKP_uefipayload" "$TMPDIR/repack/patchedKernel" "$DBKP_cfg" "$DBKP_shellcode"
mv "$TMPDIR/repack/patchedKernel" "$TMPDIR/repack/kernel"
"$TMPDIR/DBKP/magiskboot" repack "$TMPDIR/boot.img"
"$TMPDIR/DBKP/magiskboot" cleanup
cd "$TMPDIR"

ui_print "Flashing new boot.img..."
blockdev --setrw /dev/block/bootdevice/by-name/boot
cat "$TMPDIR/repack/new-boot.img" /dev/zero >/dev/block/bootdevice/by-name/boot 2>/dev/null || true
ui_print "Image patching complete!"
ui_print "Done flashing EFI!"
