#!/sbin/sh

set -euo

OUTFD=$2
ZIPFILE=$3
TMPDIR="/tmp/install"

ui_print() {
        echo "ui_print $1" >"/proc/self/fd/$OUTFD"
}

ui_print_abort() {
        ui_print "$1"
        exit 1
}

rm -rf "$TMPDIR"
mkdir -p "$TMPDIR"

unzip "$ZIPFILE" "bin/*" -d "$TMPDIR"
chmod -R 0777 "$TMPDIR/bin"

ui_print "Binary files were deployed..."

if [ ! -e /dev/block/by-name/linux ]; then
        ui_print_abort "Linux partition not found"
fi
if [ ! -e /dev/block/by-name/esp ]; then
        ui_print_abort "ESP partition not found"
fi

ui_print "Formatting and flashing Linux image"
umount -lf /dev/block/by-name/linux
blockdev --setrw /dev/block/by-name/linux
"$TMPDIR/bin/mke2fs" -F -t ext4 /dev/block/by-name/linux
"$TMPDIR/bin/7zzs" e -so "$ZIPFILE" "images/rootfs.img" >/dev/block/by-name/linux
umount -lf /dev/block/by-name/linux
ui_print "Done flashing rootfs!"

ui_print "Verifying present bootloader configration"
umount -lf /dev/block/by-name/esp
mount /dev/block/by-name/esp "$TMPDIR/esp"
rm -rf "$TMPDIR"/esp/**
mkdir "$TMPDIR/esp/EFI"
unzip "$ZIPFILE" "efi/*" -d "$TMPDIR/esp"
umount -lf /dev/block/by-name/esp
ui_print "Boot configuration setup completed!"

ui_print "Unpacking the DBKP installer..."
unzip -o "$ZIPFILE" "DBKP/*" -d "$TMPDIR"
chmod 755 "$TMPDIR/DBKP/magiskboot"
chmod 755 "$TMPDIR/DBKP/DualBootKernelPatcher"
dd if=/dev/block/bootdevice/by-name/boot of="$TMPDIR/boot.img"
ui_print "Backing up original boot.img... to /sdcard/boot.img"
rm -f /sdcard/boot.img
cp "$TMPDIR/boot.img" /sdcard/boot.img
ui_print "Repacking boot.img..."
"$TMPDIR/DBKP/magiskboot" unpack -h "$TMPDIR/boot.img"
"$TMPDIR/DBKP/DualBootKernelPatcher" kernel "$( (ls *_EFI.fd) 2>/dev/null)" patchedKernel "$( (ls DualBoot.*.cfg) 2>/dev/null)" "$( (ls ShellCode.*.bin) 2>/dev/null)"
# FIXME: there is a path problem
mv patchedKernel kernel
"$TMPDIR/DBKP/magiskboot" repack boot.img
"$TMPDIR/DBKP/magiskboot" cleanup
blockdev --setrw /dev/block/bootdevice/by-name/boot
cat new-boot.img /dev/zero >/dev/block/bootdevice/by-name/boot
ui_print "Image patching complete!"
ui_print "Done flashing EFI!"
