# Generated by AI
{
  stdenvNoCC,
  fetchurl,
}:
stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "xiaomi-nabu-firmware";
  version = "25.04.26";

  src = fetchurl {
    url = "https://gitlab.postmarketos.org/panpanpanpan/nabu-firmware/-/archive/d15fc36a670ef186ca32cdbc3e940ab18bcc2505/nabu-firmware-d15fc36a670ef186ca32cdbc3e940ab18bcc2505.tar.gz";
    hash = "sha256-DrxvWX+JJHLL5FgHjsvOuSxRUM2LstLXQNmNDJflei4=";
  };

  dontBuild = true;
  dontFixup = true;

  installPhase = ''
    mkdir -p "$out/lib/firmware/qcom/sm8150/xiaomi/nabu"
    mkdir -p "$out/lib/firmware/novatek"
    mkdir -p "$out/share/qcom/sm8150/xiaomi"

    # Adreno GPU
    install -pm644 a630_sqe.fw "$out/lib/firmware/qcom/"
    install -pm644 a640_gmu.bin "$out/lib/firmware/qcom/"
    install -pm644 a640_zap.mbn "$out/lib/firmware/qcom/sm8150/xiaomi/nabu/"

    # ADSP / CDSP / Venus / WLAN / SLPI
    for f in adsp.mbn cdsp.mbn venus.mbn wlanmdsp.mbn slpi_nb.mbn; do
      install -pm644 "$f" "$out/lib/firmware/qcom/sm8150/xiaomi/nabu/"
    done

    # Modem
    cp -r modem* "$out/lib/firmware/qcom/sm8150/xiaomi/nabu/"
    chmod 0644 "$out/lib/firmware/qcom/sm8150/xiaomi/nabu/"modem*

    # Touchscreen
    install -pm644 novatek_nt36523_fw.bin "$out/lib/firmware/novatek/"

    # HexagonFS
    cp -r hexagonfs "$out/share/qcom/sm8150/xiaomi/nabu"
  '';
})
