# Generated by AI
# see: https://github.com/nabu-alarm/alsa-ucm-conf-xiaomi-nabu/blob/main/PKGBUILD
{
  stdenvNoCC,
}:
stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "alsa-ucm-conf-xiaomi-nabu";
  version = "1.0";

  src = ./alsa-ucm-conf-xiaomi-nabu.tgz;

  dontBuild = true;
  dontFixup = true;

  sourceRoot = "src";

  installPhase = ''
    mkdir -p "$out/share"
    cp -r usr/share/alsa "$out/share/"
  '';
})
