name: Build Installer(nixos)
on: workflow_dispatch
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup Cachix cache
        uses: cachix/cachix-action@v17
        with:
          name: nixpkgs-for-nabu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Fix permissions
        run: chmod o+rx /home/runner
      - name: Build
        run: |
          nix develop --system aarch64-linux -L -c bash ./image-builder/main-plus.sh
      - name: Generate UKI and move image
        run: |
          nix build .#nixosConfigurations.default.config.system.build.uki
          mkdir ./efi/nixos ./images
          cp ./result/nixos.efi ./efi/nixos
          sudo chown -R $USER:$USER ./efi
          mv outputs/out/rootfs.img ./images
      - name: Upload partiton artifact
        uses: actions/upload-artifact@v7
        with:
          name: esp-and-rootfs-image
          path: |
            outputs/out/esp.img
            outputs/out/rootfs.img
      - name: Upload nixos artifact
        uses: actions/upload-artifact@v7
        with:
          name: nixos-nabu-installer
          path: |
            bin
            DBKP
            efi
            images
            META-INF
