name: Matrix builds
on: workflow_dispatch
jobs:
  build:
    name: Build ${{ matrix.package }}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        package:
          - alsa-ucm-conf-xiaomi-nabu
          - linux-firmware-xiaomi-nabu
          - linux-nabu
          - upower
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
      - name: Setup Cachix cache
        uses: cachix/cachix-action@v17
        with:
          name: nixpkgs-for-nabu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: |
          nix build -L .#${{ matrix.package }}
