name: Nix Cache
on: workflow_dispatch
jobs:
  nix-cache:
    name: Nix Cache
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Change the apt mirror
        uses: vegardit/fast-apt-mirror.sh@v1
      - name: Install tools
        run: sudo apt install -y qemu-user-static qemu-system qemu-system-arm qemu-system-aarch64 binfmt-support virtiofsd libfuse3-3
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # NOTE: you can get the cache by using
      # nix-store --realise /nix/store/xxxxxxxxxxxxx
      - name: Setup Cachix cache
        uses: cachix/cachix-action@v17
        with:
          name: nixpkgs-for-nabu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        run: |
          nix-build test.nix --system aarch64-linux
